In [120]:
import pandas as pd
import numpy as np

file_names = ["Smart_Investor", "Conservative_Saver", "Reckless_Spender"]
current_file = 0

df = pd.read_csv(f"app/documents/{file_names[current_file]}_200Tx.csv")

In [106]:
df.head()

,date,description,type,amount,category,month,is_credit,is_debit
0,2026-01-01,Savings Transfer,debit,44736,Savings,2026-01,False,True
1,2026-01-01,Credit,credit,5264,Unclassified,2026-01,True,False
2,2026-01-02,Salary Credit,credit,57079,Salary,2026-01,True,False
3,2026-01-02,Debit,debit,101815,Unclassified,2026-01,False,True
4,2026-01-03,Salary Credit,credit,60088,Salary,2026-01,True,False

In [107]:
df.groupby("category").size()

category
Groceries           46
Medical Expenses    19
Rent                20
Salary              28
Savings             84
Unclassified        40
dtype: int64

In [108]:
other = (
    df[df["category"] == "Unclassified"]
    ["description"]
    .value_counts()
    .head(50)
)

print(other)

description
Utilities    28
Credit        7
Debit         3
Name: count, dtype: int64

In [109]:
df["category"].value_counts()

category
Savings             84
Groceries           46
Unclassified        40
Salary              28
Rent                20
Medical Expenses    19
Name: count, dtype: int64

In [110]:
(
    df["category"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

category
Savings             35.44
Groceries           19.41
Unclassified        16.88
Salary              11.81
Rent                 8.44
Medical Expenses     8.02
Name: proportion, dtype: float64

In [111]:
other_df = (
    df[df["category"] == "Unclassified"]
)

other_df[
    ["description", "amount"]
].head()

  description  amount
1      Credit    5264
3       Debit  101815
5       Debit  161903
7      Credit    5126
9       Debit  231895

In [112]:
other_df["description"].value_counts()

description
Utilities    28
Credit        7
Debit         3
Name: count, dtype: int64

In [115]:
df[
    df["description"]
    .str.contains(
        "salary",
        case=False,
        na=False
    )
][
    ["description", "category"]
].value_counts()

description    category
Salary Credit  Salary      28
Name: count, dtype: int64

In [116]:
df[
    df["description"]
    .str.contains(
        "fd|deposit|saving|recurring",
        case=False,
        na=False
    )
][
    ["description", "category"]
].value_counts()

description       category
Savings Transfer  Savings     84
Name: count, dtype: int64

In [117]:
df.groupby("category")["amount"].agg(
    ["count", "sum", "mean", "max"]
)

                  count       sum           mean     max
category
Groceries            46    801590   17425.869565  247876
Medical Expenses     19   3440027  181054.052632  799879
Rent                 20   1274348   63717.400000  222483
Salary               28   2027188   72399.571429   89855
Savings              84  14355074  170893.738095  810204
Unclassified         40    806046   20151.150000  231895

In [118]:
(
    df["category"]
    .value_counts(normalize=True)
    * 100
).sort_values(ascending=False)

category
Savings             35.443038
Groceries           19.409283
Unclassified        16.877637
Salary              11.814346
Rent                 8.438819
Medical Expenses     8.016878
Name: proportion, dtype: float64

In [121]:
from app.services.analytics_service import category_summary

category_breakdown = category_summary(df)
print(category_breakdown)

{}